
services:

  db:
    image: postgres:16-alpine
    container_name: smarttask-db
    restart: always
    environment:
      POSTGRES_USER: smarttask
      POSTGRES_PASSWORD: smarttask
      POSTGRES_DB: smarttask_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - smarttask-net
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: smarttask-backend:latest
    container_name: smarttask-backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: smarttask
      DB_PASSWORD: smarttask
      DB_NAME: smarttask_db
      PORT: 5000
    depends_on:
      - db
    networks:
      - smarttask-net
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: smarttask-frontend:latest
    container_name: smarttask-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - smarttask-net
    ports:
      - "8080:80"

networks:
  smarttask-net:
    driver: bridge

volumes:
  db_data:
